---
- name: Install MongoDB 
  hosts: db 
  become: yes 


  tasks:
   - name: Add MongoDB repository key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-4.4.asc
        state: present

   - name: Add MongoDB repository
      apt_repository:
        repo: deb [arch=amd64] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse
        state: present
        filename: mongodb-org-4.4.list

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present
        update_cache: yes
    
    - name: Start MongoDB service
      service: 
        name: mongod 
        state: started 
        enabled: yes